name: Mesche CLI - CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get --no-install-recommends -y install pkg-config

      - name: Bootstrap CLI
        run: |
          # Run the bootstrapper script
          ./build.sh

          # Prepare a temporary build
          mkdir -p tmp
          cp bin/boot/mesche tmp
          cp -R modules tmp/

      - name: Sanity Check
        run: ./tmp/mesche

      - name: Build CLI with Mesche
        run: |
          # Clean up bin folders
          rm -rf bin deps/mesche-lang/compiler/bin

          # Run Mesche on itself to produce a release artifact
          tmp/mesche build dist --config release

      - name: Sanity Check Again
        run: ./dist/mesche

      - name: Archive workflow results
        uses: actions/upload-artifact@v2
        with:
          name: mesche-linux-x86_64
          path: dist/*
